Repository CicadaBank/bips, pull requests merged in 2023-01, with the labels that each got.

#23 Fix issue#22
  src/bips/bip32.clj
  src/bips/bip32_utils.clj
  test/bips/bip32_test.clj
Labels: bug

#28 Solve issue #27
  src/bips/bip32.clj
  test/bips/bip32_test.clj
Labels: bug

#25 Release/v0.1.2
  .github/workflows/test.yml
  README.md
  release.edn
  src/bips/bip32.clj
  src/bips/bip32_utils.clj
  src/bips/bip44.clj
  test/bips/bip32_test.clj
Labels: release

#30 Add optional argument to `derivation-path` for setting the `hardened-indicator` symbol
  src/bips/bip44.clj
  test/bips/bip44_test.clj
Labels: enhancement
